### ISSUE TITLE
nginx module

### ISSUE THREAD

**Issue by seemk** [open-telemetry/opentelemetry-cpp-contrib#4]
Hi,

I would like to contribute an nginx module which is based on opentelemetry-cpp. Would this repository be the right place?

What would the the directory structure be - each contribution in a subdirectory or would each contrib be a submodule?

With each contrib's code in a separate directory (i.e. a huge monorepo) my hunch is that handling issues might be a bit more complicated down the line. Any suggestions appreciated :slightly_smiling_face:

**Comment by lalitb** [comment]
My suggestion would be to have single mono-repo with below set of sub-directories to start with:
  - instrumentation
  -  exporters
  - propagators
 
And the under Instrumentation, we can have further:
- instrumentation/nginx
- instrumentation/apache
- instrumentation/grpc

I do understand it would be difficult to manage them down the line as the contributions increases, and that time we can decide on having CODEOWNERS for each of the contrib directories. This is how it is done in `opentelemetry-collector-contrib`: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/.github/CODEOWNERS

The releases would be source distribution for entire repo. CI would build and test required set of contrib modules, and not everything.
Let's hear from others too before finalizing.

@maxgolov  There is a PR for initial directory structure raised by you. Would you like to address the comments so that we can merge the changes to get started.

**Comment by lalitb** [comment]
Meanwhile, I would suggest you to raise a PR as discussed above, and let others comment over there.

**Comment by seemk** [comment]
Thanks @lalitb , I've opened a PR: https://github.com/open-telemetry/opentelemetry-cpp-contrib/pull/5
